export default {
    "cast": [
        {
            "adult": false,
            "gender": 2,
            "id": 2219,
            "known_for_department": "Acting",
            "name": "Tobey Maguire",
            "original_name": "Tobey Maguire",
            "popularity": 30.376,
            "profile_path": "/kOJelnLSb89SeivbOCt1l94Hz2d.jpg",
            "cast_id": 31,
            "character": "Spider-Man / Peter Parker",
            "credit_id": "52fe4251c3a36847f8014f77",
            "order": 0
        },
        {
            "adult": false,
            "gender": 2,
            "id": 5293,
            "known_for_department": "Acting",
            "name": "Willem Dafoe",
            "original_name": "Willem Dafoe",
            "popularity": 42.04,
            "profile_path": "/ui8e4sgZAwMPi3hzEO53jyBJF9B.jpg",
            "cast_id": 32,
            "character": "Green Goblin / Norman Osborn",
            "credit_id": "52fe4251c3a36847f8014f7b",
            "order": 1
        },
        {
            "adult": false,
            "gender": 1,
            "id": 205,
            "known_for_department": "Acting",
            "name": "Kirsten Dunst",
            "original_name": "Kirsten Dunst",
            "popularity": 20.435,
            "profile_path": "/6RAAxI4oPnDMzXpXWgkkzSgnIAJ.jpg",
            "cast_id": 10,
            "character": "Mary Jane Watson",
            "credit_id": "52fe4251c3a36847f8014f11",
            "order": 2
        },
        {
            "adult": false,
            "gender": 2,
            "id": 17051,
            "known_for_department": "Acting",
            "name": "James Franco",
            "original_name": "James Franco",
            "popularity": 14.532,
            "profile_path": "/rShzuvrQJJQJ6lXDn3IQX4o0iCE.jpg",
            "cast_id": 11,
            "character": "Harry Osborn",
            "credit_id": "52fe4251c3a36847f8014f15",
            "order": 3
        },
        {
            "adult": false,
            "gender": 2,
            "id": 19153,
            "known_for_department": "Acting",
            "name": "Cliff Robertson",
            "original_name": "Cliff Robertson",
            "popularity": 11.221,
            "profile_path": "/8pH2RWCPtXKzT9P33MbzgnzPlF0.jpg",
            "cast_id": 34,
            "character": "Ben Parker",
            "credit_id": "52fe4251c3a36847f8014f83",
            "order": 4
        },
        {
            "adult": false,
            "gender": 1,
            "id": 18998,
            "known_for_department": "Acting",
            "name": "Rosemary Harris",
            "original_name": "Rosemary Harris",
            "popularity": 6.115,
            "profile_path": "/rpSsXg0tB7wWQMffvvMqLzrvZAj.jpg",
            "cast_id": 35,
            "character": "May Parker",
            "credit_id": "52fe4251c3a36847f8014f87",
            "order": 5
        },
        {
            "adult": false,
            "gender": 2,
            "id": 18999,
            "known_for_department": "Acting",
            "name": "J.K. Simmons",
            "original_name": "J.K. Simmons",
            "popularity": 32.331,
            "profile_path": "/jPoNW5fugs5h8AbcE7H5OBm04Tm.jpg",
            "cast_id": 12,
            "character": "J. Jonah Jameson",
            "credit_id": "52fe4251c3a36847f8014f19",
            "order": 6
        },
        {
            "adult": false,
            "gender": 2,
            "id": 20580,
            "known_for_department": "Acting",
            "name": "Joe Manganiello",
            "original_name": "Joe Manganiello",
            "popularity": 15.06,
            "profile_path": "/mTdACmitdrwor0Nrv5sr0u123vZ.jpg",
            "cast_id": 13,
            "character": "Flash Thompson",
            "credit_id": "52fe4251c3a36847f8014f1d",
            "order": 7
        }, 
        {
            "adult": false,
            "gender": 0,
            "id": 2597781,
            "known_for_department": "Acting",
            "name": "Kristen Davidson",
            "original_name": "Kristen Davidson",
            "popularity": 0.98,
            "profile_path": "/PJEOdAYHj6eaDtWk8WhEvh5aRq.jpg",
            "cast_id": 301,
            "character": "Bone-ette",
            "credit_id": "5e91ec0400fb6b0015a3e44b",
            "order": 27
        }
    ],
    "crew": [
        {
            "adult": false,
            "gender": 2,
            "id": 508,
            "known_for_department": "Writing",
            "name": "David Koepp",
            "original_name": "David Koepp",
            "popularity": 3.455,
            "profile_path": "/srPSV5EyQomUn65ZLD45h2b0AA5.jpg",
            "credit_id": "52fe4251c3a36847f8014ef5",
            "department": "Writing",
            "job": "Screenplay"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 7623,
            "known_for_department": "Directing",
            "name": "Sam Raimi",
            "original_name": "Sam Raimi",
            "popularity": 20.584,
            "profile_path": "/ljNw0AjMKzXRvnQbgoKOsfQoVDu.jpg",
            "credit_id": "5e867154a5743d00110fe933",
            "department": "Directing",
            "job": "Director"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 9987,
            "known_for_department": "Production",
            "name": "Ian Bryce",
            "original_name": "Ian Bryce",
            "popularity": 1.988,
            "profile_path": "/hl20H0bnnBr8MG1ea52RqWBH6Iu.jpg",
            "credit_id": "52fe4251c3a36847f8014f3f",
            "department": "Production",
            "job": "Producer"
        },
        {
            "adult": false,
            "gender": 1,
            "id": 7627,
            "known_for_department": "Production",
            "name": "Laura Ziskin",
            "original_name": "Laura Ziskin",
            "popularity": 1.6,
            "profile_path": null,
            "credit_id": "52fe4251c3a36847f8014f45",
            "department": "Production",
            "job": "Producer"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 7626,
            "known_for_department": "Production",
            "name": "Avi Arad",
            "original_name": "Avi Arad",
            "popularity": 4.479,
            "profile_path": "/zFNtix6jjAfjKeE687w1VgU4H1T.jpg",
            "credit_id": "52fe4251c3a36847f8014f4b",
            "department": "Production",
            "job": "Executive Producer"
        },
        {
            "adult": false,
            "gender": 2,
            "id": 11411,
            "known_for_department": "Art",
            "name": "Neil Spisak",
            "original_name": "Neil Spisak",
            "popularity": 1.4,
            "profile_path": null,
            "credit_id": "52fe4251c3a36847f8014f51",
            "department": "Art",
            "job": "Production Design"
        },
        {
            "adult": false,
            "gender": 0,
            "id": 20585,
            "known_for_department": "Art",
            "name": "Karen O'Hara",
            "original_name": "Karen O'Hara",
            "popularity": 0.6,
            "profile_path": null,
            "credit_id": "52fe4251c3a36847f8014f5d",
            "department": "Art",
            "job": "Set Decoration"
        }
    ]
}